# Jenkins가 Pods를 관리할 권한을 가진 Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin
  # 네임스페이스를 'argocd'로 지정해야 합니다.
  # Jenkins ServiceAccount가 'argocd' 네임스페이스에 있으므로 일치시켜야 합니다.
  namespace: argocd
rules:
- apiGroups: [""] # ""는 Core API Group을 의미 (Pods, Services 등)
  resources: ["pods", "pods/exec", "pods/log", "services"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["apps"] # Deployment, StatefulSet, ReplicaSet 등
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["extensions", "networking.k8s.io"] # Ingress 등
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: [""] # ""는 Core API Group을 의미 (Pods, Services 등)
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
